project_name: freq
build:
  main: freq.go
  binary: freq
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
  goarch:
    - amd64
    - arm
    - mips
  goarm:
      - 6
      - 7
  ignore:
    - goos: freebsd
      goarch: arm
    - goos: freebsd
      goarch: mips
    - goos: windows
      goarch: arm
      goarm: 7
    - goos: windows
      goarch: arm
      goarm: 6
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
        darwin: macOS
    wrap_in_directory: true
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--sha256_checksums.txt"
release:
  draft: true


