project_name: freq
build:
  main: freq.go
  binary: freq
  ldflags: -s -w
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - arm
release:
  draft: true
